use QLSinhVien

CREATE TABLE STUDENTS
(
	MaSV VARCHAR(10) NOT NULL PRIMARY KEY,
	Hoten NVARCHAR(50) NULL,
	Email NVARCHAR(50) NULL,
	SoDT NVARCHAR(12) NULL,
	Gioitinh BIT NULL,
	Diachi NVARCHAR(100) NULL
)

SELECT * FROM STUDENTS