/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import helper.ShareData;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author NTV
 */
public class MainFrom extends javax.swing.JFrame {

    private GradePanel mGradePanel;
    private StudentPanel mStudentPanel;
    
    /**
     * Creates new form MainFrom
     */
    public MainFrom() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tplMainBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnQLSV = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnQLD = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnGioiThieu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHeThong = new javax.swing.JMenu();
        menuHeThong_DangXuat = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuHeThong_Exit = new javax.swing.JMenuItem();
        menuQL = new javax.swing.JMenu();
        menuQL_QLSV = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuQL_Diem = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuHelp_NoiDung = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuHelp_GioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sinh Viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        lblTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTen.setText("Tên :");
        jPanel1.add(lblTen);

        lblVaiTro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVaiTro.setText("Vai trò:");
        jPanel1.add(lblVaiTro);

        jToolBar1.setRollover(true);

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Log out.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);
        jToolBar1.add(jSeparator5);

        btnQLSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Clien list.png"))); // NOI18N
        btnQLSV.setText("Quản Lý Sinh Viên");
        btnQLSV.setFocusable(false);
        btnQLSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLSV);
        jToolBar1.add(jSeparator6);

        btnQLD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Numbered list.png"))); // NOI18N
        btnQLD.setText("Quản Lý Điểm");
        btnQLD.setFocusable(false);
        btnQLD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLD);
        jToolBar1.add(jSeparator7);

        btnGioiThieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Info.png"))); // NOI18N
        btnGioiThieu.setText("Giới Thiệu");
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        menuHeThong.setText("Hệ Thống");
        menuHeThong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        menuHeThong_DangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuHeThong_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Log out.png"))); // NOI18N
        menuHeThong_DangXuat.setText("Đăng Xuất");
        menuHeThong_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHeThong_DangXuatActionPerformed(evt);
            }
        });
        menuHeThong.add(menuHeThong_DangXuat);
        menuHeThong.add(jSeparator10);

        menuHeThong_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuHeThong_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Exit button.png"))); // NOI18N
        menuHeThong_Exit.setText("Thoát");
        menuHeThong_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHeThong_ExitActionPerformed(evt);
            }
        });
        menuHeThong.add(menuHeThong_Exit);

        jMenuBar1.add(menuHeThong);

        menuQL.setText("Quản lý");
        menuQL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        menuQL_QLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuQL_QLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Clien list.png"))); // NOI18N
        menuQL_QLSV.setText("Quản Lý Sinh Viên");
        menuQL_QLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQL_QLSVActionPerformed(evt);
            }
        });
        menuQL.add(menuQL_QLSV);
        menuQL.add(jSeparator9);

        menuQL_Diem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuQL_Diem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Numbered list.png"))); // NOI18N
        menuQL_Diem.setText("Quản lý điểm");
        menuQL_Diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQL_DiemActionPerformed(evt);
            }
        });
        menuQL.add(menuQL_Diem);

        jMenuBar1.add(menuQL);

        menuHelp.setText("Trợ giúp");
        menuHelp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        menuHelp_NoiDung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuHelp_NoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Document.png"))); // NOI18N
        menuHelp_NoiDung.setText("Nội Dung");
        menuHelp.add(menuHelp_NoiDung);
        menuHelp.add(jSeparator8);

        menuHelp_GioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuHelp_GioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utillies/icons/Info.png"))); // NOI18N
        menuHelp_GioiThieu.setText(" Giới Thiệu");
        menuHelp_GioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp_GioiThieuActionPerformed(evt);
            }
        });
        menuHelp.add(menuHelp_GioiThieu);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                    .addComponent(tplMainBoard))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        openLoginDialog();
        phanQuyenTruyCap();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVActionPerformed
        openTabQLSV();
    }//GEN-LAST:event_btnQLSVActionPerformed

    private void btnQLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDActionPerformed
        openTabQLDiem();
    }//GEN-LAST:event_btnQLDActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        openDialogGioiThieu();
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void menuHeThong_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHeThong_DangXuatActionPerformed
        openLoginDialog();
        phanQuyenTruyCap();
    }//GEN-LAST:event_menuHeThong_DangXuatActionPerformed

    private void menuHeThong_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHeThong_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuHeThong_ExitActionPerformed

    private void menuQL_QLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQL_QLSVActionPerformed
        openTabQLSV();
    }//GEN-LAST:event_menuQL_QLSVActionPerformed

    private void menuQL_DiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQL_DiemActionPerformed
        openTabQLDiem();
    }//GEN-LAST:event_menuQL_DiemActionPerformed

    private void menuHelp_GioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp_GioiThieuActionPerformed
        openDialogGioiThieu();
    }//GEN-LAST:event_menuHelp_GioiThieuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        openLoginDialog();
        phanQuyenTruyCap();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnQLD;
    private javax.swing.JButton btnQLSV;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenu menuHeThong;
    private javax.swing.JMenuItem menuHeThong_DangXuat;
    private javax.swing.JMenuItem menuHeThong_Exit;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuHelp_GioiThieu;
    private javax.swing.JMenuItem menuHelp_NoiDung;
    private javax.swing.JMenu menuQL;
    private javax.swing.JMenuItem menuQL_Diem;
    private javax.swing.JMenuItem menuQL_QLSV;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables

    private void openLoginDialog() {
        LoginDialog login = new LoginDialog(this, true);
        login.setVisible(true);
        
    }

    private void phanQuyenTruyCap() {
        lblTen.setText("Tên: " + ShareData.u.getUsername());
        lblVaiTro.setText("Vai trò: " +ShareData.u.getRole());
        tplMainBoard.removeAll();
        if (ShareData.u.getRole().equalsIgnoreCase("Giáo viên")) {
            menuQL_Diem.setEnabled(true);
            menuQL_QLSV.setEnabled(false);
            btnQLSV.setEnabled(false);
            btnQLD.setEnabled(true);
        } else {
            menuQL_Diem.setEnabled(false);
            menuQL_QLSV.setEnabled(true);
            btnQLSV.setEnabled(true);
            btnQLD.setEnabled(false);
        }
    }

    private void openTabQLSV() {
        if (mStudentPanel == null) {
            mStudentPanel = new StudentPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource(
                    "/utillies/icons/Clien list.png"));
            tplMainBoard.addTab("Quản Lý Sinh Viên", icon, mStudentPanel, "Quản lý sinh viên");
        }
    }

    private void openTabQLDiem() {
        if (mGradePanel == null) {
            mGradePanel = new GradePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource(
                    "/utillies/icons/Numbered list.png"));
            tplMainBoard.addTab("Quản Lý Điểm Sinh Viên", icon, mGradePanel, "Quản lý điểm sinh viên");
        }
    }

    private void openDialogGioiThieu() {
        ThongtinDialog thongtin = new ThongtinDialog(this, true);
        thongtin.setVisible(true);
    }
    
    
}
